apiVersion: devops-autopilot-crossplane-packages.io/v1alpha1
kind: BucketClass
metadata:
  name: bucket-aws-class
  labels:
    provider: aws
spec:
  compositionRef:
    name: bucket-aws-composition
  parameters:
  reclaimPolicy: Delete
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: aws-bucket-connection