apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-aws-composition
  labels:
    crossplane.io/xrd: xbuckets.devops-autopilot-crossplane-packages.io
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: devops-autopilot-crossplane-packages.io/v1alpha1
    kind: XBucket

  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: aws-bucket
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: Bucket
              metadata:
                namespace: default
              spec:
                forProvider: {}
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.namespace
                toFieldPath: metadata.namespace

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.namePrefix
                toFieldPath: spec.forProvider.bucket

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.tags
                toFieldPath: spec.forProvider.tags
                policy:
                  fromFieldPath: Optional

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.cloudProviderConfigRef
                toFieldPath: spec.providerConfigRef.name

              - type: ToCompositeFieldPath
                fromFieldPath: spec.forProvider.bucket
                toFieldPath: status.bucketName

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.bucketRegionalDomainName
                toFieldPath: status.endpointURL
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "https://%s"

          - name: aws-bucket-versioning
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: BucketVersioning
              metadata:
                namespace: default
              spec:
                forProvider:
                  bucketSelector:
                    matchControllerRef: true
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.namespace
                toFieldPath: metadata.namespace

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.versioning
                toFieldPath: spec.forProvider.versioningConfiguration.status
                transforms:
                  - type: map
                    map:
                      "true": Enabled
                      "false": Suspended

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.cloudProviderConfigRef
                toFieldPath: spec.providerConfigRef.name

          - name: aws-bucket-public-access-block
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: BucketPublicAccessBlock
              metadata:
                namespace: default
              spec:
                forProvider:
                  bucketSelector:
                    matchControllerRef: true
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.namespace
                toFieldPath: metadata.namespace

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.publicAccess
                toFieldPath: spec.forProvider.blockPublicAcls
                transforms:
                  - type: map
                    map:
                      "true": false
                      "false": true

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.publicAccess
                toFieldPath: spec.forProvider.blockPublicPolicy
                transforms:
                  - type: map
                    map:
                      "true": false
                      "false": true

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.publicAccess
                toFieldPath: spec.forProvider.ignorePublicAcls
                transforms:
                  - type: map
                    map:
                      "true": false
                      "false": true

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.publicAccess
                toFieldPath: spec.forProvider.restrictPublicBuckets
                transforms:
                  - type: map
                    map:
                      "true": false
                      "false": true

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.cloudProviderConfigRef
                toFieldPath: spec.providerConfigRef.name

          - name: aws-bucket-encryption
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: BucketServerSideEncryptionConfiguration
              metadata:
                namespace: default
              spec:
                forProvider:
                  bucketSelector:
                    matchControllerRef: true
                  rule:
                    - applyServerSideEncryptionByDefault:
                        - sseAlgorithm: AES256
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.namespace
                toFieldPath: metadata.namespace

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.cloudProviderConfigRef
                toFieldPath: spec.providerConfigRef.name

          - name: bucket-config
            base:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                namespace: default
                name: bucket-config
              data:
                bucketName: ""
                endpointURL: ""
                region: ""
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.namespace
                toFieldPath: metadata.namespace

              - type: CombineFromComposite
                toFieldPath: metadata.name
                combine:
                  strategy: string
                  string:
                    fmt: "%s-bucket"
                  variables:
                    - fromFieldPath: metadata.name

              - type: FromCompositeFieldPath
                fromFieldPath: status.bucketName
                toFieldPath: data.bucketName

              - type: FromCompositeFieldPath
                fromFieldPath: status.endpointURL
                toFieldPath: data.endpointURL

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: data.region
