apiVersion: devops-autopilot-crossplane-packages.io/v1alpha1
kind: BucketClass
metadata:
  name: bucket-azure-class
  labels:
    provider: azure
spec:
  compositionRef:
    name: bucket-azure-composition
  parameters:
  reclaimPolicy: Delete
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: azure-bucket-connection