apiVersion: devops-autopilot-crossplane-packages.io/v1alpha1
kind: XBucket
metadata:
  name: my-aws-bucket
  namespace: default
spec:
  managementPolicies:
    - "*"
  crossplane:
    compositionRef:
      name: bucket-aws-composition
  parameters:
    namePrefix: "myawsexample"
    region: "us-east-1"
    cloudProviderConfigRef: "aws-provider-config"
    tags:
      purpose: demo
      env: test
    publicAccess: false
    versioning: true
