apiVersion: devops-autopilot-crossplane-packages.io/v1alpha1
kind: XBucket
metadata:
  name: my-azure-bucket
  namespace: default
spec:
  crossplane:
    compositionRef:
      name: bucket-azure-composition
  parameters:
    namePrefix: "myazureexample"
    region: "westus2"
    resourceGroupName: "default-rg"
    cloudProviderConfigRef: "azure-provider-config"
    tags:
      purpose: demo
      env: test
    publicAccess: false
    versioning: false
