apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: database
  annotations:
    meta.crossplane.io/maintainer: Khaled Saidi
    meta.crossplane.io/source: github.com/khaledsaiidi/devops-autopilot-crossplane-packages
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Configuration package for managing PostgreSQL database abstractions on AWS Aurora and Azure Database for PostgreSQL.
spec:
  crossplane:
    version: ">=v2.0.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-rds
      version: ">=v1.20.0"
    - provider: xpkg.upbound.io/upbound/provider-azure-dbforpostgresql
      version: ">=v1.5.0"
    - function: xpkg.crossplane.io/crossplane-contrib/function-go-templating
      version: ">=v0.9.0"
    - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
      version: ">=v0.4.0"
